- hosts: "localhost"
  vars_files:
          - sec_file.yml
  tasks:
     - name: "ANSIBLE_EC2"
       ec2:
               key_name: "Uditanshu1"
               instance_type: "t2.micro"
               image: "ami-0ebc1ac48dfd14136"
               wait: yes
               count: 1
               instance_tags: 
                       Name: EC2_THROUGH_ANSIBLE
               vpc_subnet_id: "subnet-e7f7cd8f"
               assign_public_ip: yes
               region: "ap-south-1"
               state: present
               group_id: "sg-06b6b58cb591f012b"
               aws_access_key: "{{access_Key}}"
               aws_secret_key: "{{secret_Key}}"
       register: UD
     - debug:
             var: UD.instances[0].private_ip
       register: IP
     - debug: 
          var: IP["UD.instances[0].private_ip"] 
